[LWotCArmorMatters.X2DLCInfo_LWotCArmorMatters]

;Enable logging here. Only do this if you are troubleshooting
bEnableLog = false

; **********************
; *** ABLATIVE ARMOR ***
; **********************

; Enable Ablative Armor.
bEnableAblativeArmor = true

;This config makes it so that you get additional ablative points on top of the armor's original HP. 
;For example: if iAdditionalAblative = 1, and the armor has +1 HP, it will end up with +2 Ablative
; Note that unlike WOTC_AblativeToVest, LWotCArmorMatters applies this even for armors with +0 HP!
iAdditionalAblative = 1

;This is only meant for Beta Strike. If you use Beta Strike second wave option, please update this to 2
; Note that unlike WOTC_AblativeToVest, LWotCArmorMatters also applies this to the value from `iAdditionalAblative`!
iAblativeMultiplier = 1

;This config makes it so that the mod does not replace +HP with +Ablative. The mod will add
;+Ablative and leave +HP intact on the armors. This makes soldiers a lot tankier.
bStripArmorHP = false

; ***********************
; *** ARMORED PLATING ***
; ***********************

; Enable Armored Plating.
bEnableArmoredPlating = true

; This flag strips ablative HP from all platings via OPTC.
; The reason I'm not using LWotC's built-in ablative HP configs
; to zero them out is that I want bEnableArmoredPlating to *completely* disable
; the Armored Plating module, which means I'm not allowed to have AP configs
; in the LWotC namespace.
bStripAblativePlating = true

; Contains a list of all plating abilities to target.
; This serves two purposes:
; - Making it easier to make an LW2 Utility Platings compatibility patch
;   for Armored Plating.
; - Allowing compatibility with custom plating abilities, should a mod
;   ever add those. (Most mods I'm aware of just reuse the LWotC abilities.)
+CERAMIC_PLATING_ABILITIES=Ceramic_Plating_Ability
+CERAMIC_PLATING_ABILITIES=LW2WOTC_CeramicPlating_Ability
+ALLOY_PLATING_ABILITIES=Alloy_Plating_Ability
+ALLOY_PLATING_ABILITIES=LW2WOTC_AlloyPlating_Ability
+CHITIN_PLATING_ABILITIES=Chitin_Plating_Ability
+CHITIN_PLATING_ABILITIES=LW2WOTC_ChitinPlating_Ability
+CARAPACE_PLATING_ABILITIES=Carapace_Plating_Ability
+CARAPACE_PLATING_ABILITIES=LW2WOTC_CarapacePlating_Ability

; SPARKs are exempt for now, since their plating doesn't give ablative HP in 1.2.2
; but 1.2.3 overhauls SPARK armors extensively. They can equip regular platings, anyway...
;+SPARK_KEVLAR_PLATING_ABILITIES=SPARK_Kevlar_Plating_Ability
;+SPARK_PLATED_PLATING_ABILITIES=SPARK_Plated_Plating_Ability
;+SPARK_POWERED_PLATING_ABILITIES=SPARK_Powered_Plating_Ability

; Registering custom platings requires a slightly different system.
; We don't have a predetermined config key for their armor value,
; so we should use a dictionary (of sorts) instead of an array.
; +CUSTOM_PLATING_ABILITIES=(Name = MySuperPlatingAbility, Armor = 5)

; These configs determine how many points of armor a given plating type should give.
; Custom platings use a struct instead, see above example.
CERAMIC_PLATING_ARMOR=1
ALLOY_PLATING_ARMOR=2
CHITIN_PLATING_ARMOR=3
CARAPACE_PLATING_ARMOR=4

SPARK_KEVLAR_PLATING_ARMOR=0
SPARK_PLATED_PLATING_ARMOR=0
SPARK_POWERED_PLATING_ARMOR=0